apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: izk2ujysp-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/izk2ujysp-dotnet-basic